import {
  Button,
  Card,
  Avatar,
  Skeleton,
  Tag,
  List,
  Typography,
  Divider,
  Modal,
} from "antd";
import {
  DeleteOutlined,
  EditOutlined,
  FileAddOutlined,
} from "@ant-design/icons";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import useSWR from "swr";
import { gql } from "graphql-request";
import { fetcher } from "../lib/fetcher";
import React, { useState } from "react";
import Meta from "antd/lib/card/Meta";

const Home: NextPage = () => {
  const { data, error } = useSWR(
    [
      gql`
        query {
          getPosts {
            id
            title
            published
            image
            description
            content
          }
        }
      `,
    ],
    (query) => fetcher(query, {})
  );

  console.log(error);
  console.log(data);

  const { Title } = Typography;
  const [deleteModal, setDeleteModal] = useState(false);

  const showModal = () => setDeleteModal(true);
  const hideModal = () => setDeleteModal(false);

  return (
    <div>
      <Head>
        <title>Blog with postgres</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          style={{
            display: "flex",
            justifyContent: "space-around",
            alignItems: "center",
            marginTop: "10px",
          }}
        >
          <Title level={1} style={{ textAlign: "center" }}>
            CRUD Blog
          </Title>
          <Button icon={<FileAddOutlined />} type="link" href="/create-post">
            Create post
          </Button>
        </div>
        <Divider orientation="right">Read and Learn</Divider>
        <div
          style={{ padding: "0rem 0rem", height: "100vh", overflow: "auto" }}
        >
          <List
            itemLayout="vertical"
            size="large"
            dataSource={data?.getPosts.reverse()}
            renderItem={(item: any) => (
              <List.Item
                key={item?.title}
                actions={
                  !!data && [
                    <>
                      <Button icon={<EditOutlined />}>edit post</Button>
                    </>,
                    <>
                      <Button
                        danger
                        icon={<DeleteOutlined onClick={showModal} />}
                      >
                        delete post
                      </Button>
                    </>,
                  ]
                }
                extra={
                  !!data && <img width={272} alt="logo" src={item.image} />
                }
              >
                <Skeleton loading={!item} active avatar>
                  <List.Item.Meta
                    title={
                      <>
                        <a href={item.href}>{item.title}</a>{" "}
                        <Tag
                          style={{ marginLeft: 8 }}
                          color={item.published ? "success" : "error"}
                        >
                          {item.published ? "publico" : "privado"}
                        </Tag>
                      </>
                    }
                    description={item.description}
                  />
                  {item.content}
                </Skeleton>
              </List.Item>
            )}
          />
        </div>
        <Modal
          title="Esta seguro de eliminar este post"
          visible={deleteModal}
          onOk={hideModal}
          onCancel={hideModal}
          okText="Eliminar"
          cancelText="Cancelar"
        >
          <p>
            Si lo eliminas no tendras la posibilidad de recuperar el
            <strong> conocimiento</strong> depositado aqui y{" "}
            <strong>
              otras personas no tendran la posibilidad de acceder a el
            </strong>
          </p>
        </Modal>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://happy-mclean-69df89.netlify.app/"
          target="_blank"
          rel="noopener noreferrer"
          style={{
            display: "flex",
            alignItems: "center",
            gap: 6,
            justifyContent: "center",
          }}
        >
          Powered by{" "}
          <Title level={3} style={{ margin: 0 }}>
            Andres Plaza
          </Title>
        </a>
      </footer>
    </div>
  );
};

export default Home;
